import React from 'react';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import { config } from '@/lib/siwe';
import Web3ModalProvider from "@/lib/WalletConnect";
import { SidebarProvider } from '@/lib/context/SidebarContext';
import Navbar from '@/components/ui/navbar';
import Sidebar from '@/components/ui/sidebar';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Web3ModalProvider initialState={initialState}>
          <SidebarProvider>
            <div className="flex flex-col min-h-screen bg-white text-black font-mono">
              <Navbar  />
              <div className="flex flex-1">
                <Sidebar  />
                <main className="flex-1 pl-20 pt-16 pr-4 pb-4 overflow-y-auto">
                  {children}
                </main>
              </div>
            </div>
          </SidebarProvider>
        </Web3ModalProvider>
      </body>
    </html>
  );
}
